[package]
name = "requests-rocket"
version = "0.1.0"
authors = ["gf712 <gil_f.hoben@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
